# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-09 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messanger', '0002_auto_20180309_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
